import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <SideBar />
          <div className="max-width">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
